version: '3'

services:

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  extrato:
    image: "kleyssonsilva/extrato-dojo"
    ports:
      - 8083:8080
    depends_on:
      - postgres-extrato
    environment:
      DATASOURCE_HOST: jdbc:postgresql://postgres-extrato:5432/dojao
      KAFKA_BOOTSTRAP_SERVER: kafka:29092

  conta-digital:
    image: "kleyssonsilva/conta-digital-dojo"
    ports:
      - 8081:8080
    depends_on:
      - postgres-conta-digital
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres-conta-digital:5432/dojao

  email:
    image: "kleyssonsilva/email-dojo"
    ports:
      - 8082:8080
    depends_on:
      - postgres-email
    environment:
      DB_URL: jdbc:postgresql://postgres-email:5432/dojao
      KAFKA_SERVER: kafka:29092

  recarga-celular:
    image: "kleyssonsilva/recarga-celular-dojo"
    ports:
      - 8084:8080
    depends_on:
      - postgres-recarga-celular
    environment:
      DATASOURCE_HOST: jdbc:postgresql://postgres-recarga-celular:5432/dojao

  postgres-orquestrador:
    image: 'postgres:9.6-alpine'
    volumes:
      - orquestrador-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dojao
      POSTGRES_PASSWORD: dojao
      POSTGRES_DB: dojao
      POSTGRES_HOST: dojao

  postgres-conta-digital:
    image: 'postgres:9.6-alpine'
    volumes:
      - conta-digital-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: dojao
      POSTGRES_PASSWORD: dojao
      POSTGRES_DB: dojao
      POSTGRES_HOST: dojao

  postgres-email:
    image: 'postgres:9.6-alpine'
    volumes:
      - email-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: dojao
      POSTGRES_PASSWORD: dojao
      POSTGRES_DB: dojao
      POSTGRES_HOST: dojao

  postgres-extrato:
    image: 'postgres:9.6-alpine'
    volumes:
      - extrato-volume:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: dojao
      POSTGRES_PASSWORD: dojao
      POSTGRES_DB: dojao
      POSTGRES_HOST: dojao

  postgres-recarga-celular:
    image: 'postgres:9.6-alpine'
    volumes:
      - recarga-celular-volume:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: dojao
      POSTGRES_PASSWORD: dojao
      POSTGRES_DB: dojao
      POSTGRES_HOST: dojao

volumes:
  orquestrador-volume:
  extrato-volume:
  email-volume:
  conta-digital-volume:
  recarga-celular-volume:
